### ISSUE TITLE
[Feature] Add overwrite before delete

### ISSUE THREAD

**Issue by ghost** [warnakey/delete-reddit-posts#5]
Hi,
I'm sure you're aware that it is more secure to overwrite posts/comments before deletion. Please add this feature to your great program. 
Also, if you could add the ability to archive posts/comments too, that would be great. =)
Thanks again for your great and simple to use program!

**Comment by warnakey** [comment]
Hi @lucknaumann -

While I think all of those are good ideas, the number of people using the program is very small, so I think that amount of time it would take to do would not ultimately be worth it unless it served more people. I did just make an update last night though which now accounts for accounts with 2 factor authentication.

**Comment by ghost** [comment]
@warnakey  
I understand and thanks for your response. Glad that you're still making some necessary editions for better functionality!
